<?php
/**
 * Curated starter translations for the fixed website content.
 * Site owners can override every value from Appearance → Mediline Content.
 *
 * @package Mediline_Partners
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

function mediline_partners_default_content_translations() {
	return array(
		'fr' => array(
			'nav_program' => 'Programme', 'nav_how' => 'Fonctionnement', 'nav_templates' => 'Modèles de boutique', 'nav_conditions' => 'Conditions', 'nav_faq' => 'FAQ', 'nav_login' => 'Connexion', 'nav_register' => 'Inscription',
			'hero_eyebrow' => 'Programme Partenaires Mediline', 'hero_status' => 'Candidatures ouvertes', 'hero_line_1' => 'Transformez le trafic.', 'hero_line_2' => 'En revenus.', 'hero_commission' => '40–50 % de commission.', 'hero_body' => 'Lancez une boutique Mediline localisée, envoyez un trafic qualifié et gagnez sur chaque vente attribuée — avec un suivi de 90 jours et des paiements hebdomadaires.', 'hero_primary_cta' => 'Rejoindre le programme', 'hero_secondary_cta' => 'Connexion partenaire',
			'hero_proof_1_value' => '90 jours', 'hero_proof_1_label' => 'Fenêtre d’attribution', 'hero_proof_2_value' => 'Chaque semaine', 'hero_proof_2_label' => 'Paiement en USDT', 'hero_proof_3_value' => 'UE + USA', 'hero_proof_3_label' => 'Trafic approuvé', 'hero_token_1_label' => 'Commission', 'hero_token_2_label' => 'Jusqu’à', 'hero_ticket_label' => 'Vente qualifiée', 'hero_ticket_meta' => 'Paiement hebdomadaire', 'hero_caption_label' => 'Suivez chaque vente attribuée', 'hero_caption_value' => 'Gagnez. Progressez. Recommencez.', 'hero_rail_right' => 'Découvrir le programme',
			'trust_1' => '40–50 % DE COMMISSION', 'trust_2' => 'ATTRIBUTION 90 JOURS', 'trust_3' => 'EUROPE + USA', 'trust_4' => 'ACCÈS VIA PAP',
			'program_kicker' => 'Le partenariat', 'program_heading' => 'Un programme.<br>Conçu pour la <em>performance.</em>', 'program_body' => 'Mediline offre aux affiliés expérimentés les outils, le suivi et le cadre commercial nécessaires pour transformer un trafic qualifié en revenus durables.', 'program_card_1_title' => 'Visibilité<br>en temps réel.', 'program_card_1_body' => 'Analysez le trafic, les conversions et la dynamique de vos campagnes grâce à des rapports détaillés.', 'program_card_2_title' => '40–50 %<br>de commission.', 'program_card_2_body' => 'Votre taux est déterminé chaque semaine selon le nombre de ventes de la période.', 'program_card_3_title' => 'Support pensé<br>pour les partenaires.', 'program_card_3_body' => 'Profitez de conseils pratiques, de ressources éprouvées et d’un système de campagne fluide.',
			'process_kicker' => 'De la candidature au lancement', 'process_heading' => 'Cinq étapes claires.<br>Un seul système performant.', 'process_body' => 'Le site public présente les différentes boutiques. Les modèles approuvés, ressources et outils de campagne sont disponibles dans votre espace partenaire.', 'step_1_title' => 'Inscription', 'step_1_body' => 'Envoyez votre candidature via Post Affiliate Pro.', 'step_2_title' => 'Validation', 'step_2_body' => 'Nous évaluons votre expérience, votre profil de trafic et votre marché cible.', 'step_3_title' => 'Choix de la boutique', 'step_3_body' => 'Sélectionnez le modèle adapté à votre campagne et à votre audience.', 'step_4_title' => 'Langue et région', 'step_4_body' => 'Préparez une version pour un marché européen ou américain approuvé.', 'step_5_title' => 'Lancement et optimisation', 'step_5_body' => 'Mettez en ligne, suivez les résultats et optimisez avec des données réelles.',
			'templates_kicker' => 'Six systèmes distincts', 'templates_heading' => 'Six boutiques.<br>Un moteur de performance.', 'templates_body' => 'Chaque aperçu propose un rythme, une audience et une logique visuelle différents. Ouvrez un modèle pour l’examiner en détail.', 'templates_note_title' => 'Les modèles sont présentés ici uniquement à titre de démonstration.', 'templates_note_body' => 'Les partenaires approuvés accèdent aux modèles de boutique et aux ressources après connexion au panneau d’affiliation Post Affiliate Pro.',
			'benefits_kicker' => 'L’avantage partenaire', 'benefits_heading' => 'Pensé pour convertir.<br>Conçu pour <em>progresser.</em>', 'benefits_portal_label' => 'PERFORMANCE PARTENAIRE / LIVE', 'benefits_rate_label' => 'TAUX', 'benefits_cookie_label' => 'COOKIE', 'benefits_payout_label' => 'PAIEMENT', 'benefit_1_title' => 'Une commission compétitive', 'benefit_1_body' => 'Gagnez 40–50 %, avec un taux hebdomadaire déterminé par le volume de ventes.', 'benefit_2_title' => 'Analyses de performance', 'benefit_2_body' => 'Suivez le trafic, les conversions et les gains grâce à des données transparentes.', 'benefit_3_title' => 'Support partenaire', 'benefit_3_body' => 'Recevez des conseils et ressources pour lancer, apprendre et optimiser.', 'benefit_4_title' => 'Opérations simplifiées', 'benefit_4_body' => 'Gérez le suivi et les supports approuvés via Post Affiliate Pro.',
			'conditions_kicker' => 'Conditions du programme', 'conditions_heading' => 'Des chiffres clairs.<br>Des conditions réelles.', 'conditions_body' => 'Les principales règles commerciales sont publiées dès le départ. Vos ventes, votre taux hebdomadaire et vos paiements restent visibles dans le panneau affilié.', 'commission_kicker' => 'Modèle de commission', 'commission_heading' => '40–50 %<br>par vente', 'commission_body' => 'Le pourcentage dépend du nombre de ventes de la période, est fixé chaque semaine et ne change pas rétroactivement.',
			'condition_1_label' => 'Commission', 'condition_2_label' => 'Révision du taux', 'condition_2_value' => 'Hebdomadaire, selon les ventes', 'condition_3_label' => 'Paiement', 'condition_3_value' => 'Une fois par semaine', 'condition_4_label' => 'Devise de paiement', 'condition_5_label' => 'Paiement minimum', 'condition_6_label' => 'Durée du cookie', 'condition_6_value' => '90 jours', 'traffic_1_label' => 'Géographie du trafic', 'traffic_1_value' => 'Pays européens + États-Unis', 'traffic_2_label' => 'Sources de trafic', 'traffic_2_value' => 'Tous les types sauf les méthodes interdites', 'traffic_3_label' => 'Non accepté', 'traffic_3_value' => 'Fraude, trafic incité, spam, bots, fraude au clic et PPC de marque non approuvé', 'conditions_footnote' => 'La commission est comptabilisée uniquement sur les commandes payées. Les annulations, remboursements et rétrofacturations peuvent l’annuler. Les frais de paiement sont à la charge de l’affilié.',
			'faq_kicker' => 'Vos questions, nos réponses', 'faq_heading' => 'L’essentiel du<br>programme partenaire.', 'cta_kicker' => 'Votre prochaine campagne commence ici', 'cta_heading' => 'Donnez plus de valeur<br>à votre <em>trafic.</em>', 'cta_body' => 'Rejoignez Mediline Partners pour un lancement plus clair, une meilleure visibilité et une commission qui récompense les résultats.', 'cta_register' => 'S’inscrire comme partenaire', 'cta_login' => 'Connexion partenaire', 'footer_note' => 'Les ressources de boutique sont disponibles après validation dans le panneau affilié PAP.', 'footer_tagline' => 'La performance, en toute clarté.', 'terms_kicker' => 'Programme Partenaires Mediline', 'terms_heading' => 'Conditions<br><em>du programme.</em>', 'terms_updated' => 'Conditions historiques du programme', 'terms_intro' => 'Ces conditions présentent les règles commerciales du programme d’affiliation Mediline et peuvent être modifiées depuis WordPress.', 'terms_body' => '<h2>1. Commission</h2><p>Les affiliés approuvés perçoivent une commission de <strong>40–50 %</strong> sur les ventes éligibles. Le taux dépend des performances de la période, est révisé chaque semaine et n’est pas modifié rétroactivement.</p><h2>2. Suivi et attribution</h2><p>Les recommandations sont suivies pendant <strong>90 jours</strong>. Une vente doit être correctement attribuée via le système de suivi Mediline.</p><h2>3. Paiements</h2><p>Les paiements sont effectués <strong>une fois par semaine</strong> en <strong>USDT</strong>. Le seuil minimum est de <strong>100 USDT</strong>. Les frais de transfert sont à la charge de l’affilié.</p><h2>4. Commissions valides</h2><p>La commission est acquise uniquement sur les commandes payées. Annulations, remboursements, rétrofacturations et fraude peuvent annuler la commission.</p><h2>5. Marchés approuvés</h2><p>Le programme accepte le trafic approuvé provenant des <strong>pays européens et des États-Unis</strong>.</p><h2>6. Sources de trafic</h2><p>Sont interdits : fraude, trafic incité non approuvé, spam, bots, fraude au clic et campagnes PPC non approuvées utilisant la marque Mediline.</p><h2>7. Conformité</h2><p>L’affilié reste responsable de la légalité et de l’exactitude de ses activités promotionnelles.</p><h2>8. Administration</h2><p>Les ventes, le taux de commission et les paiements sont visibles dans le panneau affilié. Mediline peut vérifier la qualité du trafic et les transactions éligibles.</p>',
			'login_kicker' => 'Accès sécurisé', 'login_heading' => 'Heureux de<br>vous revoir.', 'login_body' => 'Connectez-vous pour accéder à votre espace partenaire Post Affiliate Pro.', 'login_visual_kicker' => 'Votre espace de performance', 'login_visual_heading' => 'Suivez.<br>Apprenez.<br><em>Progressez.</em>', 'register_kicker' => 'Candidatures ouvertes', 'register_heading' => 'Créez votre<br>prochain canal<br>de revenus.', 'register_body' => 'Présentez-vous. Chaque candidature est examinée avant l’accès aux boutiques et aux outils de campagne.', 'register_visual_kicker' => 'La performance, en toute clarté', 'register_visual_heading' => 'Du trafic<br>aux <em>revenus.</em>',
		),
		'de' => array(
			'nav_program' => 'Programm', 'nav_how' => 'Ablauf', 'nav_templates' => 'Shop-Vorlagen', 'nav_conditions' => 'Bedingungen', 'nav_faq' => 'FAQ', 'nav_login' => 'Anmelden', 'nav_register' => 'Registrieren',
			'hero_eyebrow' => 'Mediline Partnerprogramm', 'hero_status' => 'Bewerbungen offen', 'hero_line_1' => 'Traffic verwandeln.', 'hero_line_2' => 'In Umsatz.', 'hero_commission' => '40–50 % Provision.', 'hero_body' => 'Starten Sie einen lokalisierten Mediline-Shop, senden Sie qualifizierten Traffic und verdienen Sie an jedem zugeordneten Verkauf — mit 90-Tage-Tracking und wöchentlichen Auszahlungen.', 'hero_primary_cta' => 'Für das Programm bewerben', 'hero_secondary_cta' => 'Partner-Login',
			'hero_proof_1_value' => '90 Tage', 'hero_proof_1_label' => 'Attributionsfenster', 'hero_proof_2_value' => 'Wöchentlich', 'hero_proof_2_label' => 'USDT-Auszahlung', 'hero_proof_3_value' => 'EU + USA', 'hero_proof_3_label' => 'Freigegebener Traffic', 'hero_token_1_label' => 'Provision', 'hero_token_2_label' => 'Bis zu', 'hero_ticket_label' => 'Qualifizierter Verkauf', 'hero_ticket_meta' => 'Wöchentliche Auszahlung', 'hero_caption_label' => 'Jeden Verkauf nachvollziehen', 'hero_caption_value' => 'Verdienen. Wachsen. Wiederholen.', 'hero_rail_right' => 'Programm entdecken',
			'trust_1' => '40–50 % PROVISION', 'trust_2' => '90-TAGE-ATTRIBUTION', 'trust_3' => 'EUROPA + USA', 'trust_4' => 'PAP-ZUGANG',
			'program_kicker' => 'Die Partnerschaft', 'program_heading' => 'Ein Programm.<br>Für <em>Performance</em> entwickelt.', 'program_body' => 'Mediline gibt erfahrenen Affiliates die Tools, das Tracking und die kommerzielle Struktur, um qualifizierten Traffic in nachhaltigen Umsatz zu verwandeln.', 'program_card_1_title' => 'Echtzeit-<br>Transparenz.', 'program_card_1_body' => 'Verstehen Sie Traffic, Conversions und Kampagnenentwicklung mit detaillierten Berichten.', 'program_card_2_title' => '40–50 %<br>Provision.', 'program_card_2_body' => 'Ihr Satz wird wöchentlich anhand der Verkäufe im Berichtszeitraum bestimmt.', 'program_card_3_title' => 'Support für<br>Partner.', 'program_card_3_body' => 'Erhalten Sie praktische Hilfe, bewährte Ressourcen und ein effizientes Kampagnensystem.',
			'process_kicker' => 'Von der Bewerbung bis zum Start', 'process_heading' => 'Fünf klare Schritte.<br>Ein Performance-System.', 'process_body' => 'Die öffentliche Website zeigt die verfügbaren Shop-Richtungen. Freigegebene Vorlagen, Ressourcen und Kampagnen-Tools liegen im Partnerbereich.', 'step_1_title' => 'Registrieren', 'step_1_body' => 'Senden Sie Ihre Bewerbung über Post Affiliate Pro.', 'step_2_title' => 'Freigabe erhalten', 'step_2_body' => 'Wir prüfen Ihre Erfahrung, Ihr Traffic-Profil und Ihren Zielmarkt.', 'step_3_title' => 'Shop auswählen', 'step_3_body' => 'Wählen Sie die passende Vorlage für Kampagne und Zielgruppe.', 'step_4_title' => 'Sprache und Region', 'step_4_body' => 'Bereiten Sie die Version für einen freigegebenen Markt in Europa oder den USA vor.', 'step_5_title' => 'Starten und optimieren', 'step_5_body' => 'Gehen Sie live, messen Sie Ergebnisse und optimieren Sie mit echten Daten.',
			'templates_kicker' => 'Sechs eigenständige Systeme', 'templates_heading' => 'Sechs Shops.<br>Ein Performance-Kern.', 'templates_body' => 'Jede Vorschau folgt einem anderen Kampagnenrhythmus, Publikum und visuellen Prinzip. Öffnen Sie eine Richtung für mehr Details.', 'templates_note_title' => 'Die Vorlagen werden hier nur zur Demonstration gezeigt.', 'templates_note_body' => 'Freigegebene Partner erhalten nach der Anmeldung im Post Affiliate Pro Panel Zugriff auf Shop-Vorlagen und Ressourcen.',
			'benefits_kicker' => 'Der Partner-Vorteil', 'benefits_heading' => 'Für Conversion gemacht.<br>Zum <em>Verbessern</em> gebaut.', 'benefits_portal_label' => 'PARTNER-PERFORMANCE / LIVE', 'benefits_rate_label' => 'SATZ', 'benefits_cookie_label' => 'COOKIE', 'benefits_payout_label' => 'AUSZAHLUNG', 'benefit_1_title' => 'Attraktive Provision', 'benefit_1_body' => 'Verdienen Sie 40–50 %, wöchentlich bestimmt durch Ihr Verkaufsvolumen.', 'benefit_2_title' => 'Performance-Analysen', 'benefit_2_body' => 'Überwachen Sie Traffic, Conversions und Ertrag mit transparenten Daten.', 'benefit_3_title' => 'Partner-Support', 'benefit_3_body' => 'Nutzen Sie Beratung und Ressourcen für Start, Lernen und Optimierung.', 'benefit_4_title' => 'Effiziente Abläufe', 'benefit_4_body' => 'Verwalten Sie Tracking und freigegebene Materialien über Post Affiliate Pro.',
			'conditions_kicker' => 'Programmbedingungen', 'conditions_heading' => 'Klare Zahlen.<br>Echte Bedingungen.', 'conditions_body' => 'Die wichtigsten Konditionen sind von Anfang an transparent. Verkäufe, Wochensatz und Auszahlungen bleiben im Affiliate-Panel sichtbar.', 'commission_kicker' => 'Provisionsmodell', 'commission_heading' => '40–50 %<br>pro Verkauf', 'commission_body' => 'Der Prozentsatz hängt von den Verkäufen im Berichtszeitraum ab, wird wöchentlich festgelegt und nicht rückwirkend geändert.',
			'condition_1_label' => 'Provision', 'condition_2_label' => 'Satzprüfung', 'condition_2_value' => 'Wöchentlich, nach Verkäufen', 'condition_3_label' => 'Auszahlung', 'condition_3_value' => 'Einmal pro Woche', 'condition_4_label' => 'Auszahlungswährung', 'condition_5_label' => 'Mindestauszahlung', 'condition_6_label' => 'Cookie-Laufzeit', 'condition_6_value' => '90 Tage', 'traffic_1_label' => 'Traffic-Regionen', 'traffic_1_value' => 'Europäische Länder + USA', 'traffic_2_label' => 'Traffic-Quellen', 'traffic_2_value' => 'Alle Arten außer verbotenen Methoden', 'traffic_3_label' => 'Nicht akzeptiert', 'traffic_3_value' => 'Betrug, Incentive-Traffic, Spam, Bots, Klickbetrug und nicht genehmigtes Brand-PPC', 'conditions_footnote' => 'Provision entsteht nur für erfolgreich bezahlte Bestellungen. Stornos, Erstattungen und Rückbuchungen können sie aufheben. Zahlungsgebühren trägt der Affiliate.',
			'faq_kicker' => 'Fragen und Antworten', 'faq_heading' => 'Das Wichtigste zum<br>Partnerprogramm.', 'cta_kicker' => 'Ihre nächste Kampagne beginnt hier', 'cta_heading' => 'Machen Sie mehr<br>aus Ihrem <em>Traffic.</em>', 'cta_body' => 'Mediline Partners bietet einen klareren Start, transparente Performance und ein Provisionsmodell, das Ergebnisse belohnt.', 'cta_register' => 'Als Partner registrieren', 'cta_login' => 'Partner-Login', 'footer_note' => 'Shop-Ressourcen sind nach der Freigabe im PAP Affiliate Panel verfügbar.', 'footer_tagline' => 'Performance, sichtbar gemacht.', 'terms_kicker' => 'Mediline Partnerprogramm', 'terms_heading' => 'Programm-<br><em>bedingungen.</em>', 'terms_updated' => 'Bisherige Programmbedingungen', 'terms_intro' => 'Diese Bedingungen beschreiben die kommerziellen Regeln des Mediline Partnerprogramms und können in WordPress bearbeitet werden.', 'terms_body' => '<h2>1. Provision</h2><p>Freigegebene Affiliates erhalten <strong>40–50 %</strong> Provision auf qualifizierte Verkäufe. Der Satz richtet sich nach der Performance des Berichtszeitraums, wird wöchentlich geprüft und nicht rückwirkend geändert.</p><h2>2. Tracking und Attribution</h2><p>Empfehlungen werden <strong>90 Tage</strong> verfolgt. Ein Verkauf muss über das freigegebene Mediline-Tracking korrekt zugeordnet werden.</p><h2>3. Auszahlungen</h2><p>Auszahlungen erfolgen <strong>einmal pro Woche</strong> in <strong>USDT</strong>. Die Mindestauszahlung beträgt <strong>100 USDT</strong>. Transfergebühren trägt der Affiliate.</p><h2>4. Gültige Provisionen</h2><p>Provision entsteht nur für bezahlte Bestellungen. Stornos, Rückerstattungen, Chargebacks oder Betrug können die Provision aufheben.</p><h2>5. Freigegebene Märkte</h2><p>Akzeptiert wird genehmigter Traffic aus <strong>europäischen Ländern und den USA</strong>.</p><h2>6. Traffic-Quellen</h2><p>Nicht zulässig sind Betrug, nicht genehmigter Incentive-Traffic, Spam, Bots, Click-Fraud und nicht genehmigte Brand-PPC-Kampagnen.</p><h2>7. Compliance</h2><p>Affiliates sind für die Rechtmäßigkeit und Richtigkeit ihrer Werbung verantwortlich.</p><h2>8. Programmverwaltung</h2><p>Verkäufe, Provisionssatz und Auszahlungen sind im Affiliate-Panel sichtbar. Mediline kann Traffic-Qualität und qualifizierte Transaktionen prüfen.</p>',
			'login_kicker' => 'Sicherer Zugang', 'login_heading' => 'Willkommen<br>zurück.', 'login_body' => 'Melden Sie sich an, um Ihren Post Affiliate Pro Partnerbereich zu öffnen.', 'login_visual_kicker' => 'Ihr Performance-Bereich', 'login_visual_heading' => 'Messen.<br>Lernen.<br><em>Wachsen.</em>', 'register_kicker' => 'Bewerbungen offen', 'register_heading' => 'Ihr nächster<br>Umsatzkanal<br>beginnt hier.', 'register_body' => 'Erzählen Sie uns von sich. Jede Bewerbung wird vor dem Zugriff auf Shops und Kampagnen-Tools geprüft.', 'register_visual_kicker' => 'Performance, sichtbar gemacht', 'register_visual_heading' => 'Von Traffic<br>zu <em>Umsatz.</em>',
		),
		'sp' => array(
			'nav_program' => 'Programa', 'nav_how' => 'Cómo funciona', 'nav_templates' => 'Plantillas', 'nav_conditions' => 'Condiciones', 'nav_faq' => 'FAQ', 'nav_login' => 'Acceder', 'nav_register' => 'Registrarse',
			'hero_eyebrow' => 'Programa de Socios Mediline', 'hero_status' => 'Solicitudes abiertas', 'hero_line_1' => 'Convierte tráfico.', 'hero_line_2' => 'En ingresos.', 'hero_commission' => '40–50 % de comisión.', 'hero_body' => 'Lanza una tienda Mediline localizada, envía tráfico cualificado y gana por cada venta atribuida — con seguimiento de 90 días y pagos semanales.', 'hero_primary_cta' => 'Solicitar acceso', 'hero_secondary_cta' => 'Acceso de socios',
			'hero_proof_1_value' => '90 días', 'hero_proof_1_label' => 'Ventana de atribución', 'hero_proof_2_value' => 'Semanal', 'hero_proof_2_label' => 'Pago en USDT', 'hero_proof_3_value' => 'UE + EE. UU.', 'hero_proof_3_label' => 'Tráfico aprobado', 'hero_token_1_label' => 'Comisión', 'hero_token_2_label' => 'Hasta', 'hero_ticket_label' => 'Venta cualificada', 'hero_ticket_meta' => 'Pago semanal', 'hero_caption_label' => 'Sigue cada venta atribuida', 'hero_caption_value' => 'Gana. Crece. Repite.', 'hero_rail_right' => 'Explorar el programa',
			'trust_1' => '40–50 % DE COMISIÓN', 'trust_2' => 'ATRIBUCIÓN DE 90 DÍAS', 'trust_3' => 'EUROPA + EE. UU.', 'trust_4' => 'ACCESO CON PAP',
			'program_kicker' => 'La colaboración', 'program_heading' => 'Un programa.<br>Creado para el <em>rendimiento.</em>', 'program_body' => 'Mediline ofrece a afiliados con experiencia las herramientas, el seguimiento y la estructura comercial para convertir tráfico cualificado en ingresos sostenibles.', 'program_card_1_title' => 'Visibilidad<br>en tiempo real.', 'program_card_1_body' => 'Comprende el tráfico, las conversiones y el impulso de las campañas con informes detallados.', 'program_card_2_title' => '40–50 %<br>de comisión.', 'program_card_2_body' => 'Tu porcentaje se determina cada semana según las ventas del periodo.', 'program_card_3_title' => 'Soporte para<br>socios.', 'program_card_3_body' => 'Obtén orientación práctica, recursos probados y un sistema ágil para tus campañas.',
			'process_kicker' => 'De la solicitud al lanzamiento', 'process_heading' => 'Cinco pasos claros.<br>Un sistema de rendimiento.', 'process_body' => 'El sitio público muestra las distintas tiendas. Las plantillas aprobadas, los recursos y las herramientas están en tu espacio de socio.', 'step_1_title' => 'Regístrate', 'step_1_body' => 'Envía tu solicitud mediante Post Affiliate Pro.', 'step_2_title' => 'Recibe aprobación', 'step_2_body' => 'Revisamos tu experiencia, perfil de tráfico y mercado objetivo.', 'step_3_title' => 'Elige una tienda', 'step_3_body' => 'Selecciona la plantilla adecuada para tu campaña y audiencia.', 'step_4_title' => 'Idioma y región', 'step_4_body' => 'Prepara una versión para un mercado aprobado de Europa o EE. UU.', 'step_5_title' => 'Lanza y optimiza', 'step_5_body' => 'Publica, mide resultados y mejora las campañas con datos reales.',
			'templates_kicker' => 'Seis sistemas diferentes', 'templates_heading' => 'Seis tiendas.<br>Un núcleo de rendimiento.', 'templates_body' => 'Cada vista explora un ritmo, una audiencia y una lógica visual distintos. Abre cualquier opción para verla en detalle.', 'templates_note_title' => 'Las plantillas se muestran solo con fines de demostración.', 'templates_note_body' => 'Los socios aprobados acceden a las plantillas y recursos después de entrar al panel de afiliados de Post Affiliate Pro.',
			'benefits_kicker' => 'La ventaja del socio', 'benefits_heading' => 'Hecho para convertir.<br>Creado para <em>mejorar.</em>', 'benefits_portal_label' => 'RENDIMIENTO DE SOCIOS / LIVE', 'benefits_rate_label' => 'TASA', 'benefits_cookie_label' => 'COOKIE', 'benefits_payout_label' => 'PAGO', 'benefit_1_title' => 'Comisión competitiva', 'benefit_1_body' => 'Gana entre 40 y 50 %, con un porcentaje semanal según el volumen de ventas.', 'benefit_2_title' => 'Analítica de rendimiento', 'benefit_2_body' => 'Controla tráfico, conversiones e ingresos con datos transparentes.', 'benefit_3_title' => 'Soporte para socios', 'benefit_3_body' => 'Recibe orientación y recursos para lanzar, aprender y optimizar.', 'benefit_4_title' => 'Operaciones simplificadas', 'benefit_4_body' => 'Gestiona el seguimiento y los materiales aprobados mediante Post Affiliate Pro.',
			'conditions_kicker' => 'Condiciones del programa', 'conditions_heading' => 'Números claros.<br>Condiciones reales.', 'conditions_body' => 'Las reglas comerciales principales se publican desde el principio. Tus ventas, porcentaje semanal y pagos están visibles en el panel.', 'commission_kicker' => 'Modelo de comisión', 'commission_heading' => '40–50 %<br>por venta', 'commission_body' => 'El porcentaje depende de las ventas del periodo, se determina cada semana y no cambia de forma retroactiva.',
			'condition_1_label' => 'Comisión', 'condition_2_label' => 'Revisión del porcentaje', 'condition_2_value' => 'Semanal, por ventas', 'condition_3_label' => 'Pago', 'condition_3_value' => 'Una vez por semana', 'condition_4_label' => 'Moneda de pago', 'condition_5_label' => 'Pago mínimo', 'condition_6_label' => 'Periodo de cookie', 'condition_6_value' => '90 días', 'traffic_1_label' => 'Geografía del tráfico', 'traffic_1_value' => 'Países europeos + EE. UU.', 'traffic_2_label' => 'Fuentes de tráfico', 'traffic_2_value' => 'Todos los tipos excepto los métodos prohibidos', 'traffic_3_label' => 'No aceptado', 'traffic_3_value' => 'Fraude, tráfico incentivado, spam, bots, fraude de clics y PPC de marca no aprobado', 'conditions_footnote' => 'La comisión se genera solo en pedidos pagados. Cancelaciones, reembolsos y contracargos pueden anularla. Las comisiones del sistema de pago corren a cargo del afiliado.',
			'faq_kicker' => 'Preguntas y respuestas', 'faq_heading' => 'Lo esencial del<br>programa de socios.', 'cta_kicker' => 'Tu próxima campaña empieza aquí', 'cta_heading' => 'Haz que tu tráfico<br>valga <em>más.</em>', 'cta_body' => 'Únete a Mediline Partners para lanzar con claridad, medir el rendimiento y obtener una comisión que premia los resultados.', 'cta_register' => 'Registrarse como socio', 'cta_login' => 'Acceso de socios', 'footer_note' => 'Los recursos de tienda están disponibles tras la aprobación en el panel de afiliados PAP.', 'footer_tagline' => 'Rendimiento visible.', 'terms_kicker' => 'Programa de socios Mediline', 'terms_heading' => 'Términos y<br><em>condiciones.</em>', 'terms_updated' => 'Condiciones históricas del programa', 'terms_intro' => 'Estas condiciones describen las reglas comerciales del programa de afiliados de Mediline y pueden editarse desde WordPress.', 'terms_body' => '<h2>1. Comisión</h2><p>Los afiliados aprobados reciben una comisión del <strong>40–50 %</strong> sobre las ventas válidas. El porcentaje depende del rendimiento del periodo, se revisa semanalmente y no se cambia retroactivamente.</p><h2>2. Seguimiento y atribución</h2><p>Las referencias se rastrean durante <strong>90 días</strong>. La venta debe atribuirse correctamente mediante el sistema de seguimiento aprobado de Mediline.</p><h2>3. Pagos</h2><p>Los pagos se procesan <strong>una vez por semana</strong> en <strong>USDT</strong>. El mínimo es de <strong>100 USDT</strong>. Las comisiones de transferencia corren a cargo del afiliado.</p><h2>4. Comisiones válidas</h2><p>La comisión solo se genera en pedidos pagados. Cancelaciones, reembolsos, contracargos o fraude pueden anularla.</p><h2>5. Mercados aprobados</h2><p>Se acepta tráfico aprobado de <strong>países europeos y Estados Unidos</strong>.</p><h2>6. Fuentes de tráfico</h2><p>No se acepta fraude, tráfico incentivado no aprobado, spam, bots, fraude de clics ni PPC de marca no aprobado.</p><h2>7. Cumplimiento</h2><p>El afiliado es responsable de que su actividad promocional sea legal y exacta.</p><h2>8. Administración</h2><p>Las ventas, el porcentaje y los pagos se muestran en el panel de afiliados. Mediline puede revisar la calidad del tráfico y las transacciones válidas.</p>',
			'login_kicker' => 'Acceso seguro', 'login_heading' => 'Te damos la<br>bienvenida.', 'login_body' => 'Inicia sesión para acceder a tu espacio de socio de Post Affiliate Pro.', 'login_visual_kicker' => 'Tu espacio de rendimiento', 'login_visual_heading' => 'Mide.<br>Aprende.<br><em>Crece.</em>', 'register_kicker' => 'Solicitudes abiertas', 'register_heading' => 'Crea tu<br>próximo canal<br>de ingresos.', 'register_body' => 'Cuéntanos quién eres. Revisamos cada solicitud antes de habilitar las tiendas y herramientas de campaña.', 'register_visual_kicker' => 'Rendimiento visible', 'register_visual_heading' => 'Del tráfico<br>a los <em>ingresos.</em>',
		),
		'it' => array(
			'nav_program' => 'Programma', 'nav_how' => 'Come funziona', 'nav_templates' => 'Template', 'nav_conditions' => 'Condizioni', 'nav_faq' => 'FAQ', 'nav_login' => 'Accedi', 'nav_register' => 'Registrati',
			'hero_eyebrow' => 'Programma Partner Mediline', 'hero_status' => 'Candidature aperte', 'hero_line_1' => 'Trasforma il traffico.', 'hero_line_2' => 'In ricavi.', 'hero_commission' => '40–50% di commissione.', 'hero_body' => 'Lancia uno storefront Mediline localizzato, invia traffico qualificato e guadagna su ogni vendita attribuita — con tracciamento di 90 giorni e pagamenti settimanali.', 'hero_primary_cta' => 'Candidati al programma', 'hero_secondary_cta' => 'Accesso partner',
			'hero_proof_1_value' => '90 giorni', 'hero_proof_1_label' => 'Finestra di attribuzione', 'hero_proof_2_value' => 'Settimanale', 'hero_proof_2_label' => 'Pagamento in USDT', 'hero_proof_3_value' => 'UE + USA', 'hero_proof_3_label' => 'Traffico approvato', 'hero_token_1_label' => 'Commissione', 'hero_token_2_label' => 'Fino al', 'hero_ticket_label' => 'Vendita qualificata', 'hero_ticket_meta' => 'Pagamento settimanale', 'hero_caption_label' => 'Traccia ogni vendita attribuita', 'hero_caption_value' => 'Guadagna. Cresci. Ripeti.', 'hero_rail_right' => 'Esplora il programma',
			'trust_1' => '40–50% DI COMMISSIONE', 'trust_2' => 'ATTRIBUZIONE 90 GIORNI', 'trust_3' => 'EUROPA + USA', 'trust_4' => 'ACCESSO CON PAP',
			'program_kicker' => 'La partnership', 'program_heading' => 'Un programma.<br>Creato per la <em>performance.</em>', 'program_body' => 'Mediline offre agli affiliati esperti strumenti, tracciamento e una struttura commerciale per trasformare il traffico qualificato in ricavi sostenibili.', 'program_card_1_title' => 'Visibilità<br>in tempo reale.', 'program_card_1_body' => 'Comprendi traffico, conversioni e andamento delle campagne con report dettagliati.', 'program_card_2_title' => '40–50%<br>di commissione.', 'program_card_2_body' => 'La percentuale viene definita ogni settimana in base alle vendite del periodo.', 'program_card_3_title' => 'Supporto pensato<br>per i partner.', 'program_card_3_body' => 'Ricevi indicazioni pratiche, risorse collaudate e un sistema efficiente per le campagne.',
			'process_kicker' => 'Dalla candidatura al lancio', 'process_heading' => 'Cinque passaggi chiari.<br>Un sistema di performance.', 'process_body' => 'Il sito pubblico mostra le diverse direzioni degli storefront. Template, risorse e strumenti approvati si trovano nell’area partner.', 'step_1_title' => 'Registrati', 'step_1_body' => 'Invia la candidatura tramite Post Affiliate Pro.', 'step_2_title' => 'Ottieni l’approvazione', 'step_2_body' => 'Valutiamo esperienza, profilo di traffico e mercato target.', 'step_3_title' => 'Scegli lo storefront', 'step_3_body' => 'Seleziona il template adatto alla campagna e al pubblico.', 'step_4_title' => 'Lingua e regione', 'step_4_body' => 'Prepara la versione per un mercato europeo o statunitense approvato.', 'step_5_title' => 'Lancia e ottimizza', 'step_5_body' => 'Vai online, misura le performance e migliora le campagne con dati reali.',
			'templates_kicker' => 'Sei sistemi distinti', 'templates_heading' => 'Sei storefront.<br>Un unico motore.', 'templates_body' => 'Ogni anteprima esplora ritmo, pubblico e logica visiva differenti. Apri una direzione per osservarla nel dettaglio.', 'templates_note_title' => 'I template sono mostrati solo a scopo dimostrativo.', 'templates_note_body' => 'I partner approvati accedono ai template e alle risorse dopo il login nel pannello affiliati Post Affiliate Pro.',
			'benefits_kicker' => 'Il vantaggio partner', 'benefits_heading' => 'Creato per convertire.<br>Pronto a <em>migliorare.</em>', 'benefits_portal_label' => 'PERFORMANCE PARTNER / LIVE', 'benefits_rate_label' => 'TASSO', 'benefits_cookie_label' => 'COOKIE', 'benefits_payout_label' => 'PAGAMENTO', 'benefit_1_title' => 'Commissione competitiva', 'benefit_1_body' => 'Guadagna il 40–50%, con percentuale settimanale determinata dal volume di vendite.', 'benefit_2_title' => 'Analisi delle performance', 'benefit_2_body' => 'Monitora traffico, conversioni e guadagni con dati trasparenti.', 'benefit_3_title' => 'Supporto partner', 'benefit_3_body' => 'Ottieni indicazioni e risorse per lanciare, imparare e ottimizzare.', 'benefit_4_title' => 'Operazioni semplificate', 'benefit_4_body' => 'Gestisci tracciamento e materiali approvati tramite Post Affiliate Pro.',
			'conditions_kicker' => 'Condizioni del programma', 'conditions_heading' => 'Numeri chiari.<br>Condizioni reali.', 'conditions_body' => 'Le principali regole commerciali sono pubblicate in anticipo. Vendite, percentuale settimanale e pagamenti restano visibili nel pannello.', 'commission_kicker' => 'Modello di commissione', 'commission_heading' => '40–50%<br>per vendita', 'commission_body' => 'La percentuale dipende dalle vendite del periodo, viene definita ogni settimana e non cambia retroattivamente.',
			'condition_1_label' => 'Commissione', 'condition_2_label' => 'Revisione del tasso', 'condition_2_value' => 'Settimanale, per vendite', 'condition_3_label' => 'Pagamento', 'condition_3_value' => 'Una volta a settimana', 'condition_4_label' => 'Valuta di pagamento', 'condition_5_label' => 'Pagamento minimo', 'condition_6_label' => 'Durata del cookie', 'condition_6_value' => '90 giorni', 'traffic_1_label' => 'Aree geografiche', 'traffic_1_value' => 'Paesi europei + USA', 'traffic_2_label' => 'Fonti di traffico', 'traffic_2_value' => 'Tutti i tipi tranne i metodi vietati', 'traffic_3_label' => 'Non accettato', 'traffic_3_value' => 'Frode, traffico incentivato, spam, bot, click fraud e PPC sul brand non approvato', 'conditions_footnote' => 'La commissione matura solo sugli ordini pagati. Cancellazioni, rimborsi e chargeback possono annullarla. Le commissioni del sistema di pagamento sono a carico dell’affiliato.',
			'faq_kicker' => 'Domande e risposte', 'faq_heading' => 'Gli elementi chiave del<br>programma partner.', 'cta_kicker' => 'La prossima campagna inizia qui', 'cta_heading' => 'Dai più valore<br>al tuo <em>traffico.</em>', 'cta_body' => 'Unisciti a Mediline Partners per un lancio più chiaro, performance visibili e una commissione che premia i risultati.', 'cta_register' => 'Registrati come partner', 'cta_login' => 'Accesso partner', 'footer_note' => 'Le risorse storefront sono disponibili dopo l’approvazione nel pannello affiliati PAP.', 'footer_tagline' => 'Performance, resa visibile.', 'terms_kicker' => 'Programma Partner Mediline', 'terms_heading' => 'Termini e<br><em>condizioni.</em>', 'terms_updated' => 'Condizioni storiche del programma', 'terms_intro' => 'Queste condizioni descrivono le regole commerciali del programma affiliati Mediline e possono essere modificate da WordPress.', 'terms_body' => '<h2>1. Commissione</h2><p>I partner approvati ricevono una commissione del <strong>40–50%</strong> sulle vendite valide. La percentuale dipende dalle performance del periodo, viene verificata ogni settimana e non cambia retroattivamente.</p><h2>2. Tracciamento e attribuzione</h2><p>I referral vengono tracciati per <strong>90 giorni</strong>. La vendita deve essere attribuita correttamente tramite il sistema Mediline approvato.</p><h2>3. Pagamenti</h2><p>I pagamenti vengono elaborati <strong>una volta a settimana</strong> in <strong>USDT</strong>. Il minimo è di <strong>100 USDT</strong>. Le commissioni di trasferimento sono a carico dell’affiliato.</p><h2>4. Commissioni valide</h2><p>La commissione matura solo sugli ordini pagati. Cancellazioni, rimborsi, chargeback o frodi possono annullarla.</p><h2>5. Mercati approvati</h2><p>È accettato traffico approvato da <strong>paesi europei e Stati Uniti</strong>.</p><h2>6. Fonti di traffico</h2><p>Non sono ammessi frode, traffico incentivato non approvato, spam, bot, click fraud e PPC sul brand non approvato.</p><h2>7. Conformità</h2><p>L’affiliato è responsabile della legalità e dell’accuratezza della propria attività promozionale.</p><h2>8. Amministrazione</h2><p>Vendite, percentuale e pagamenti sono visibili nel pannello affiliati. Mediline può verificare qualità del traffico e transazioni valide.</p>',
			'login_kicker' => 'Accesso sicuro', 'login_heading' => 'Bentornato.', 'login_body' => 'Accedi per continuare nel tuo spazio partner Post Affiliate Pro.', 'login_visual_kicker' => 'Il tuo spazio performance', 'login_visual_heading' => 'Misura.<br>Impara.<br><em>Cresci.</em>', 'register_kicker' => 'Candidature aperte', 'register_heading' => 'Crea il tuo<br>prossimo canale<br>di ricavi.', 'register_body' => 'Raccontaci chi sei. Ogni candidatura viene verificata prima di rendere disponibili storefront e strumenti.', 'register_visual_kicker' => 'Performance, resa visibile', 'register_visual_heading' => 'Dal traffico<br>ai <em>ricavi.</em>',
		),
	);
}
